### ISSUE TITLE
missing changelog.md file

### ISSUE THREAD

**Issue by Stromweld** [sous-chefs/nano#20]
Would be nice to have changelog.md file so it also shows up in the community supermarket page for this cookbook.

**Comment by Stromweld** [comment]
also don't for get to remove this line so that it gets uploaded to the supermarket. https://github.com/sous-chefs/nano/blob/92b69df0d2858aeffac5660a1ad1f392163b2d66/chefignore#L93

**Comment by Xorima** [comment]
Done and uploaded. 
Changelog is there
